### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [linuxdeepin/deepin-music#47]
Hi. I'm a graphic designer. I wanted to contribute to your project and I've designed a logo for your project. If you like it, you can use it. it's free. I'll send you files and pr. tell me if you need anything change i'll fix it. thanks.
Best regard.
![deepin](https://user-images.githubusercontent.com/36124339/42413020-36c0e0ce-8242-11e8-86c6-a2589d5bfcab.png)

**Comment by Iceyer** [comment]
I am very glad to receive you work for this project. But the project logo is designed by our design department, and we do not accept single icon since we have our design style, we must keep it the same in one system. However, you can upload you icon with svg format here, so any one who like it can download it and replace the system default icon.
